# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_who',
            field=models.CharField(default='0', max_length=200, verbose_name='谁发布的'),
        ),
    ]
