# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'ordering': ('pub_time',),
            },
        ),
    ]
