# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名ͧ字ͧ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价ͧ格ͧ')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='优ͧ惠ͧ')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='图ͧ片ͧ')),
                ('desc', models.CharField(max_length=500, verbose_name='描ͧ述ͧ')),
                ('label', models.CharField(max_length=400, verbose_name='标ͧ签ͧ')),
                ('order', models.IntegerField(default=0, verbose_name='权ͧ重ͧ')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_post', to='cake.Category')),
            ],
            options={
                'verbose_name': '蛋ͧ糕ͧ详ͧ情ͧ',
                'verbose_name_plural': '蛋ͧ糕ͧ详ͧ情ͧ',
                'ordering': ('pub_time',),
            },
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
